///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("62544184-0689-4263-bd4b-5d9f25eb8ace", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTestRepository repository.
        /// </summary>
        public static MyTestRepository repo = MyTestRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LogIn' at 73;198.", repo.LogIn.SelfInfo, new RecordItemIndex(0));
            repo.LogIn.Self.Click("73;198");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'admin' with focus on 'LogIn'.", repo.LogIn.SelfInfo, new RecordItemIndex(1));
            repo.LogIn.Self.EnsureVisible();
            Keyboard.Press("admin");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LogIn.Text' at 117;5.", repo.LogIn.TextInfo, new RecordItemIndex(2));
            repo.LogIn.Text.Click("117;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '123' with focus on 'LogIn.Text'.", repo.LogIn.TextInfo, new RecordItemIndex(3));
            repo.LogIn.Text.PressKeys("123");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LogIn.CbIsAdmin' at 5;11.", repo.LogIn.CbIsAdminInfo, new RecordItemIndex(4));
            repo.LogIn.CbIsAdmin.Click("5;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LogIn.BtnLogin' at 47;30.", repo.LogIn.BtnLoginInfo, new RecordItemIndex(5));
            repo.LogIn.BtnLogin.Click("47;30");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AplicacionTienda.ButtonOK' at 60;9.", repo.AplicacionTienda.ButtonOKInfo, new RecordItemIndex(6));
            repo.AplicacionTienda.ButtonOK.Click("60;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MenuPrincipalAdmin.PanelDesktop' at -45;281.", repo.MenuPrincipalAdmin.PanelDesktopInfo, new RecordItemIndex(7));
            repo.MenuPrincipalAdmin.PanelDesktop.Click("-45;281");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MenuPrincipalAdmin.BtnAddUser' at 81;19.", repo.MenuPrincipalAdmin.BtnAddUserInfo, new RecordItemIndex(8));
            repo.MenuPrincipalAdmin.BtnAddUser.Click("81;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MenuPrincipalAdmin.AgregarUsuario1.AgregarUsuario' at 108;69.", repo.MenuPrincipalAdmin.AgregarUsuario1.AgregarUsuarioInfo, new RecordItemIndex(9));
            repo.MenuPrincipalAdmin.AgregarUsuario1.AgregarUsuario.Click("108;69");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MenuPrincipalAdmin.AgregarUsuario1.AgregarUsuario' at 125;89.", repo.MenuPrincipalAdmin.AgregarUsuario1.AgregarUsuarioInfo, new RecordItemIndex(10));
            repo.MenuPrincipalAdmin.AgregarUsuario1.AgregarUsuario.Click("125;89");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'sergio' with focus on 'MenuPrincipalAdmin'.", repo.MenuPrincipalAdmin.SelfInfo, new RecordItemIndex(11));
            repo.MenuPrincipalAdmin.Self.EnsureVisible();
            Keyboard.Press("sergio");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MenuPrincipalAdmin.AgregarUsuario1.Nombre' at 65;71.", repo.MenuPrincipalAdmin.AgregarUsuario1.NombreInfo, new RecordItemIndex(12));
            repo.MenuPrincipalAdmin.AgregarUsuario1.Nombre.Click("65;71");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '123' with focus on 'MenuPrincipalAdmin'.", repo.MenuPrincipalAdmin.SelfInfo, new RecordItemIndex(13));
            repo.MenuPrincipalAdmin.Self.EnsureVisible();
            Keyboard.Press("123");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MenuPrincipalAdmin.AgregarUsuario1.AgregarUsuario' at 174;227.", repo.MenuPrincipalAdmin.AgregarUsuario1.AgregarUsuarioInfo, new RecordItemIndex(14));
            repo.MenuPrincipalAdmin.AgregarUsuario1.AgregarUsuario.Click("174;227");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '123' with focus on 'MenuPrincipalAdmin'.", repo.MenuPrincipalAdmin.SelfInfo, new RecordItemIndex(15));
            repo.MenuPrincipalAdmin.Self.EnsureVisible();
            Keyboard.Press("123");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MenuPrincipalAdmin.AgregarUsuario1.Direccion' at 67;93.", repo.MenuPrincipalAdmin.AgregarUsuario1.DireccionInfo, new RecordItemIndex(16));
            repo.MenuPrincipalAdmin.AgregarUsuario1.Direccion.Click("67;93");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '123' with focus on 'MenuPrincipalAdmin'.", repo.MenuPrincipalAdmin.SelfInfo, new RecordItemIndex(17));
            repo.MenuPrincipalAdmin.Self.EnsureVisible();
            Keyboard.Press("123");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MenuPrincipalAdmin.AgregarUsuario1.AgregarUsuario' at 730;75.", repo.MenuPrincipalAdmin.AgregarUsuario1.AgregarUsuarioInfo, new RecordItemIndex(18));
            repo.MenuPrincipalAdmin.AgregarUsuario1.AgregarUsuario.Click("730;75");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.ADMIN' at 225;3.", repo.List1000.ADMINInfo, new RecordItemIndex(19));
            repo.List1000.ADMIN.Click("225;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MenuPrincipalAdmin.AgregarUsuario1.AgregarUsuario' at 646;161.", repo.MenuPrincipalAdmin.AgregarUsuario1.AgregarUsuarioInfo, new RecordItemIndex(20));
            repo.MenuPrincipalAdmin.AgregarUsuario1.AgregarUsuario.Click("646;161");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'sergio' with focus on 'MenuPrincipalAdmin'.", repo.MenuPrincipalAdmin.SelfInfo, new RecordItemIndex(21));
            repo.MenuPrincipalAdmin.Self.EnsureVisible();
            Keyboard.Press("sergio");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MenuPrincipalAdmin.AgregarUsuario1.Tipo' at 106;90.", repo.MenuPrincipalAdmin.AgregarUsuario1.TipoInfo, new RecordItemIndex(22));
            repo.MenuPrincipalAdmin.AgregarUsuario1.Tipo.Click("106;90");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '123' with focus on 'MenuPrincipalAdmin'.", repo.MenuPrincipalAdmin.SelfInfo, new RecordItemIndex(23));
            repo.MenuPrincipalAdmin.Self.EnsureVisible();
            Keyboard.Press("123");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MenuPrincipalAdmin.AgregarUsuario1.BtnAdd' at 110;19.", repo.MenuPrincipalAdmin.AgregarUsuario1.BtnAddInfo, new RecordItemIndex(24));
            repo.MenuPrincipalAdmin.AgregarUsuario1.BtnAdd.Click("110;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Aviso.ButtonOK' at 28;8.", repo.Aviso.ButtonOKInfo, new RecordItemIndex(25));
            repo.Aviso.ButtonOK.Click("28;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MenuPrincipalAdmin.AgregarUsuario1.BtnAdd' at -646;-35.", repo.MenuPrincipalAdmin.AgregarUsuario1.BtnAddInfo, new RecordItemIndex(26));
            repo.MenuPrincipalAdmin.AgregarUsuario1.BtnAdd.Click("-646;-35");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
